html:
	mkdir -p siden && asciidoctor -a lang=da kristian_nygaard_jensen.adoc -o siden/index.html

pdf:
	asciidoctor-pdf -a allow-uri-read kristian_nygaard_jensen.adoc

pdf_en:
	asciidoctor-pdf -a allow-uri-read kristian_nygaard_jensen_en.adoc
